"""
STRATEGY CALENDAR — Per-day P&L for every v3-v14 strategy.
Reads trade data from strategy_trades.json and stats from strategy_stats.json
(both generated by compute_stats.py) to ensure a single source of truth.

Usage:  python compute_stats.py && python strategy_calendar.py
Output: strategy_calendar.html
"""

import os, json, calendar
from datetime import datetime
from collections import defaultdict

_DIR = os.path.dirname(os.path.abspath(__file__))

# ═══════════════════════════════════════════════════════════════════════
# STRATEGY METADATA  (colors + regime labels for display)
# ═══════════════════════════════════════════════════════════════════════
STRATEGIES = [
    {"ver":"v3", "name":"PHOENIX",        "short":"PHX", "regime":"PHOENIX",        "mech":"50%/close/1T","filter":"--",              "color":"#f59e0b"},
    {"ver":"n15","name":"PHOENIX CLEAR",  "short":"CLR", "regime":"PHOENIX_CLEAR",  "mech":"50%/close/1T","filter":"VIX9D/VIX<1.0",  "color":"#22c55e"},
    {"ver":"v6", "name":"QUIET REBOUND",  "short":"QRB", "regime":"LOW_DN_IN_GFL",  "mech":"50%/1530/1T", "filter":"VP<=1.7",        "color":"#06b6d4"},
    {"ver":"v7", "name":"FLAT-GAP FADE",  "short":"FGF", "regime":"LOW_FL_IN_GUP",  "mech":"40%/close/1T","filter":"--",              "color":"#a855f7"},
    {"ver":"v8", "name":"STRESS SNAP",    "short":"SNP", "regime":"ELEV_UP_IN_GDN", "mech":"40%/1530/1T", "filter":"--",              "color":"#ef4444"},
    {"ver":"v9", "name":"BREAKOUT STALL", "short":"BKT", "regime":"MID_UP_OT_GFL",  "mech":"70%/1545/1T", "filter":"!RISING",        "color":"#eab308"},
    {"ver":"v10","name":"BREAKDOWN PAUSE","short":"BKD", "regime":"MID_DN_OT_GFL",  "mech":"70%/1545/1T", "filter":"--",              "color":"#ec4899"},
    {"ver":"v12","name":"BULL SQUEEZE",   "short":"BSQ", "regime":"LOW_UP_OT_GUP",  "mech":"40%/close/1T","filter":"5dRet>1",        "color":"#f97316"},
    {"ver":"v14","name":"ORDERLY DIP",    "short":"DIP", "regime":"MID_DN_IN_GDN",  "mech":"50%/close/1T","filter":"ScoreVol<18",    "color":"#64748b"},
    {"ver":"n17","name":"AFTERNOON LOCK", "short":"AFT", "regime":"PHOENIX_AFT",    "mech":"50%/close/1T","filter":"VVIX<100@13:00", "color":"#7c3aed"},
    {"ver":"n18","name":"LATE SQUEEZE",   "short":"LSQ", "regime":"LATE_SQUEEZE",   "mech":"50%/close/1T","filter":"3Laws@14:00",    "color":"#0ea5e9"},
]

color_map = {s["ver"]: s["color"] for s in STRATEGIES}
short_map = {s["ver"]: s["short"] for s in STRATEGIES}
name_map  = {s["ver"]: s["name"]  for s in STRATEGIES}
ver_list  = [s["ver"] for s in STRATEGIES]

# ═══════════════════════════════════════════════════════════════════════
# LOAD DATA (from compute_stats.py output)
# ═══════════════════════════════════════════════════════════════════════
print("Loading trade data from compute_stats.py output...", flush=True)

trades_path = os.path.join(_DIR, "strategy_trades.json")
stats_path = os.path.join(_DIR, "strategy_stats.json")

if not os.path.exists(trades_path) or not os.path.exists(stats_path):
    print("ERROR: Run compute_stats.py first to generate strategy_trades.json and strategy_stats.json")
    exit(1)

with open(trades_path) as f:
    all_trades = json.load(f)

with open(stats_path) as f:
    all_stats = json.load(f)

print(f"  {len(all_trades)} trades loaded across {len(all_stats)} strategies")

# ═══════════════════════════════════════════════════════════════════════
# BUILD CALENDAR DATA (group trades by date)
# ═══════════════════════════════════════════════════════════════════════
calendar_data = {}  # date -> {ver -> trade_info}
combined_daily = {}  # date -> total dollar PnL

for t in all_trades:
    d = t["date"]
    if d not in calendar_data:
        calendar_data[d] = {}
    calendar_data[d][t["ver"]] = t

for d, trades in calendar_data.items():
    combined_daily[d] = sum(t["pnl"] for t in trades.values())

# Compute cumulative P&L per strategy
cum_by_strat = {s["ver"]: 0 for s in STRATEGIES}
for d_str in sorted(calendar_data.keys()):
    for ver, trade in calendar_data[d_str].items():
        cum_by_strat[ver] += trade["pnl"]
        trade["cum_pnl"] = cum_by_strat[ver]

# Print summary
total_all = sum(s.get("total_pnl", 0) for s in all_stats.values())
print(f"\n  {'Strat':<6} {'Days':>5} {'WR':>6} {'Total $':>12} {'Avg $':>10}")
print(f"  {'-----':<6} {'----':>5} {'-----':>6} {'-------':>12} {'-----':>10}")
for s in STRATEGIES:
    st = all_stats.get(s["ver"], {})
    n = st.get("total_trades", 0)
    if n == 0: continue
    wr = st.get("win_rate", 0)
    total = st.get("total_pnl", 0)
    avg = st.get("avg_pnl", 0)
    print(f"  {s['ver'].upper():<6} {n:>5} {wr:>5.1f}% ${total:>11,} ${avg:>9,}")

print(f"\n  COMBINED TOTAL: ${total_all:,}")

# ═══════════════════════════════════════════════════════════════════════
# GENERATE HTML CALENDAR
# ═══════════════════════════════════════════════════════════════════════
print("\nGenerating HTML calendar...", flush=True)

all_dates = sorted(calendar_data.keys())
first_date = datetime.strptime(all_dates[0], "%Y-%m-%d")
last_date = datetime.strptime(all_dates[-1], "%Y-%m-%d")

months = []
current = first_date.replace(day=1)
while current <= last_date:
    months.append((current.year, current.month))
    if current.month == 12:
        current = current.replace(year=current.year + 1, month=1)
    else:
        current = current.replace(month=current.month + 1)

html = """<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Strategy Calendar -- v3-v14 Dollar P&L ($100K Risk)</title>
<style>
* { box-sizing: border-box; margin: 0; padding: 0; }
body { background: #0a0a0f; color: #e0e0e0; font-family: 'Consolas', 'Monaco', monospace; padding: 20px; }
h1 { color: #f59e0b; font-size: 20px; margin-bottom: 4px; }
.subtitle { color: #888; font-size: 11px; margin-bottom: 16px; }
.legend { display: flex; flex-wrap: wrap; gap: 8px; margin-bottom: 16px; padding: 10px; background: #111118; border-radius: 6px; border: 1px solid #222; }
.legend-item { display: flex; align-items: center; gap: 4px; font-size: 10px; }
.legend-dot { width: 10px; height: 10px; border-radius: 2px; }
.stats-table { width: 100%; border-collapse: collapse; margin-bottom: 24px; font-size: 11px; }
.stats-table th { text-align: left; padding: 6px 10px; border-bottom: 2px solid #333; color: #888; font-weight: normal; text-transform: uppercase; font-size: 9px; letter-spacing: 1px; }
.stats-table td { padding: 5px 10px; border-bottom: 1px solid #1a1a22; }
.stats-table tr:hover { background: #111118; }
.month-section { margin-bottom: 28px; }
.month-title { font-size: 14px; color: #ccc; margin-bottom: 8px; padding: 4px 10px; background: #111118; border-radius: 4px; display: inline-block; }
.cal-grid { display: grid; grid-template-columns: repeat(7, 1fr); gap: 2px; }
.cal-hdr { font-size: 9px; color: #666; text-align: center; padding: 4px; }
.cal-day { background: #0f0f16; border: 1px solid #1a1a22; border-radius: 4px; min-height: 68px; padding: 3px; font-size: 9px; }
.cal-day.empty { background: transparent; border-color: transparent; min-height: 20px; }
.cal-day.has-trades { border-color: #333; }
.cal-day .day-num { color: #666; font-size: 10px; margin-bottom: 2px; }
.cal-day .day-num.weekend { color: #333; }
.strat-tag { display: inline-block; padding: 1px 4px; border-radius: 2px; font-size: 8px; font-weight: bold; margin: 1px; line-height: 1.4; white-space: nowrap; }
.strat-tag.win { opacity: 1; }
.strat-tag.loss { opacity: 0.7; }
.pnl-pos { color: #22c55e; }
.pnl-neg { color: #ef4444; }
.day-total { font-size: 9px; font-weight: bold; margin-top: 2px; padding-top: 2px; border-top: 1px solid #222; }
</style>
</head>
<body>
<h1>STRATEGY CALENDAR -- All Strategies Dollar P&L</h1>
<div class="subtitle">Risk: PHOENIX/PHOENIX CLEAR tiered $25K–$100K | QUIET REBOUND/BREAKDOWN PAUSE/BULL SQUEEZE/ORDERLY DIP $75K | BREAKOUT STALL $100K | FLAT-GAP FADE/STRESS SNAP $25K | AFTERNOON LOCK/LATE SQUEEZE $50K fixed | VP-scaled per trade | $1/spread slippage | N17/N18 use real bid/ask fills</div>

<div class="legend">
"""

for s in STRATEGIES:
    html += f'<div class="legend-item"><div class="legend-dot" style="background:{s["color"]}"></div>{s["name"]} <span style="opacity:0.5;font-size:9px;">{s["ver"].upper()}</span></div>\n'

html += '</div>\n'

# Stats summary table (from strategy_stats.json)
html += '<table class="stats-table">\n'
html += '<tr><th>Strategy</th><th>Regime</th><th>Mech</th><th>Filter</th><th>Days</th><th>W/L</th><th>Win Rate</th><th>Total P&L</th><th>Avg P&L</th><th>PF</th><th>Max DD</th></tr>\n'
for s in STRATEGIES:
    st = all_stats.get(s["ver"], {})
    n = st.get("total_trades", 0)
    if n == 0: continue
    wr = st.get("win_rate", 0)
    wins = st.get("wins", 0)
    losses = st.get("losses", 0)
    total = st.get("total_pnl", 0)
    avg = st.get("avg_pnl", 0)
    pf = st.get("profit_factor", 0)
    mdd = st.get("max_drawdown", 0)
    pnl_class = "pnl-pos" if total >= 0 else "pnl-neg"
    html += f'<tr><td style="color:{s["color"]};font-weight:bold">{s["name"]} <span style="opacity:0.45;font-size:9px;font-weight:normal">{s["ver"].upper()}</span></td>'
    html += f'<td>{s["regime"]}</td><td>{s["mech"]}</td><td>{s["filter"]}</td>'
    html += f'<td>{n}</td><td>{wins}/{losses}</td>'
    html += f'<td>{wr:.1f}%</td>'
    html += f'<td class="{pnl_class}">${total:,.0f}</td>'
    html += f'<td class="{pnl_class}">${avg:,.0f}</td>'
    html += f'<td>{pf:.2f}</td>'
    html += f'<td class="pnl-neg">${mdd:,.0f}</td></tr>\n'

# Total row
html += f'<tr style="border-top:2px solid #444;font-weight:bold"><td colspan="7" style="color:#f59e0b">COMBINED</td>'
html += f'<td class="{"pnl-pos" if total_all >= 0 else "pnl-neg"}">${total_all:,.0f}</td><td colspan="3"></td></tr>\n'
html += '</table>\n'

# Month calendars
DOW_NAMES = ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"]

def fmt_pnl(v):
    """Format dollar P&L compactly: +1.2K, -500, +23K"""
    if abs(v) >= 1000:
        return f"{'+' if v >= 0 else ''}{v/1000:.1f}K"
    else:
        return f"{'+' if v >= 0 else ''}{v:.0f}"

for year, month in reversed(months):
    month_name = calendar.month_name[month]

    # Month total
    month_total = 0
    for d_str, total in combined_daily.items():
        d = datetime.strptime(d_str, "%Y-%m-%d")
        if d.year == year and d.month == month:
            month_total += total

    pnl_cls = "pnl-pos" if month_total >= 0 else "pnl-neg"
    html += f'<div class="month-section">\n'
    html += f'<div class="month-title">{month_name} {year} <span class="{pnl_cls}" style="margin-left:12px">${month_total:,.0f}</span></div>\n'
    html += '<div class="cal-grid">\n'

    for d in DOW_NAMES:
        html += f'<div class="cal-hdr">{d}</div>\n'

    first_dow = datetime(year, month, 1).weekday()
    days_in_month = calendar.monthrange(year, month)[1]

    for _ in range(first_dow):
        html += '<div class="cal-day empty"></div>\n'

    for day in range(1, days_in_month + 1):
        d_str = f"{year}-{month:02d}-{day:02d}"
        dow = datetime(year, month, day).weekday()
        is_weekend = dow >= 5

        day_trades = calendar_data.get(d_str, {})
        has_trades = len(day_trades) > 0

        cls = "cal-day"
        if has_trades: cls += " has-trades"

        html += f'<div class="{cls}">\n'
        html += f'<div class="day-num{"" if not is_weekend else " weekend"}">{day}</div>\n'

        if has_trades:
            total_pnl = 0
            for ver in ver_list:
                if ver in day_trades:
                    t = day_trades[ver]
                    pnl = t["pnl"]
                    total_pnl += pnl
                    win_cls = "win" if pnl >= 0 else "loss"
                    sign_cls = "pnl-pos" if pnl >= 0 else "pnl-neg"
                    qty_str = f"{t['qty']}x"
                    fc_str = f" ({t['fire_count']}sig)" if t.get("fire_count") else ""
                    exit_label = t.get("exit", "?")
                    risk_k = t.get("risk_budget", 100000) / 1000
                    tooltip = f"{name_map.get(ver, ver.upper())} ({ver.upper()}) {exit_label} | {qty_str}{fc_str} | ${pnl:+,} (${risk_k:.0f}K risk)"
                    html += f'<span class="strat-tag {win_cls}" style="background:{color_map[ver]}22;color:{color_map[ver]};border:1px solid {color_map[ver]}44" '
                    html += f'title="{tooltip}">'
                    html += f'{short_map.get(ver, ver[1:])} <span class="{sign_cls}">{fmt_pnl(pnl)}</span>'
                    html += '</span>\n'

            sign_cls = "pnl-pos" if total_pnl >= 0 else "pnl-neg"
            html += f'<div class="day-total {sign_cls}">{fmt_pnl(total_pnl)}</div>\n'

        html += '</div>\n'

    remaining = (7 - (first_dow + days_in_month) % 7) % 7
    for _ in range(remaining):
        html += '<div class="cal-day empty"></div>\n'

    html += '</div></div>\n'

html += '</body></html>'

out_path = os.path.join(_DIR, "strategy_calendar.html")
with open(out_path, "w", encoding="utf-8") as f:
    f.write(html)

print(f"\nCalendar saved to: {out_path}")
